CI Github Action: generate artifacts in step 'Run Testsuite'
Calling TAR ourselves might overcome a bug in actions/upload-artifact@v2
which hangs for some reason.

Changes suggested by ZW.

* .github/workflows/build.yml:
  - testsuite for each platform: tar the testdir and print testsuite.log
    to the CI-log
  - pass tar.gz to actions/upload-artifact@v2
  - fix typos

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -31,7 +31,7 @@ jobs:
             base-devel
             msys2-devel
       - name: Require git-clone without EOL changes
-        # ... otherwise BUILD (autoconf.texi and other documentation friends) fwill fail.
+        # ... otherwise BUILD (autoconf.texi and other documentation friends) might fail.
         run: |
           git config --global core.autocrlf false
           git config --global --list
@@ -51,18 +51,21 @@ jobs:
         working-directory: build
       - name: Run Testsuite
         if: ${{ success() }}
-        run: make check TESTSUITEFLAGS='-j16' || make check TESTSUITEFLAGS='--recheck -j16 -v -x -d'
+        run: |
+          make check TESTSUITEFLAGS='-j16' || {
+            cd tests
+            echo === Contents of testsuite.log ===
+            cat testsuite.log
+            echo === End of testsuite.log ===
+            tar -czf msys2-testsuite.dir.tar.gz testsuite.dir
+            exit 1
+          }
         working-directory: build
-      - name: Generate Artifacts upon Failure
+      - name: Upload Artifact upon Failure
         if: ${{ failure() }}
         uses: actions/upload-artifact@v2
         with:
-          name: MSYS-failure
-          path: |
-            build/config.*
-            build/tests/**
-            !build/**/at-job-fifo.*
-            !build/**/*.lnk
+          path: build/tests/msys2-testsuite.dir.tar.gz
 
   macos:
     runs-on: macos-latest
@@ -77,7 +80,7 @@ jobs:
       - name: Init OSX-System
         run: brew install autoconf automake gettext texinfo help2man
       - name: Require git-clone without EOL changes
-        # ... otherwise BUILD (autoconf.texi and other documentation friends) fwill fail.
+        # ... otherwise BUILD (autoconf.texi and other documentation friends) might fail.
         run: |
           git config --global core.autocrlf false
           git config --global --list
@@ -97,8 +100,22 @@ jobs:
         working-directory: build
       - name: Run Testsuite
         if: ${{ success() }}
-        run: make check TESTSUITEFLAGS='-j16' || make check TESTSUITEFLAGS='--recheck -j16 -v -x -d'
+        run: |
+          make check TESTSUITEFLAGS='-j16' || {
+            cd tests
+            echo === Contents of testsuite.log ===
+            cat testsuite.log
+            echo === End of testsuite.log ===
+            tar -czf macos-testsuite.dir.tar.gz testsuite.dir
+            exit 1
+          }
         working-directory: build
+      - name: Upload Artifact upon Failure
+        if: ${{ failure() }}
+        uses: actions/upload-artifact@v2
+        with:
+          name: Unix-failure
+          path: build/tests/macos-testsuite.dir.tar.gz
 
   unix:
     runs-on: ubuntu-latest
@@ -113,7 +130,7 @@ jobs:
       - name: Init UNIX-System
         run: brew install autoconf automake gettext texinfo help2man
       - name: Require git-clone without EOL changes
-        # ... otherwise BUILD (autoconf.texi and other documentation friends) fwill fail.
+        # ... otherwise BUILD (autoconf.texi and other documentation friends) might fail.
         run: |
           git config --global core.autocrlf false
           git config --global --list
@@ -133,15 +150,19 @@ jobs:
         working-directory: build
       - name: Run Testsuite
         if: ${{ success() }}
-        run: make check TESTSUITEFLAGS='-j16' || make check TESTSUITEFLAGS='--recheck -j16 -v -x -d'
+        run: |
+          make check TESTSUITEFLAGS='-j16' || {
+            cd tests
+            echo === Contents of testsuite.log ===
+            cat testsuite.log
+            echo === End of testsuite.log ===
+            tar -czf unix-testsuite.dir.tar.gz testsuite.dir
+            exit 1
+          }
         working-directory: build
-      - name: Generate Artifacts upon Failure
+      - name: Upload Artifact upon Failure
         if: ${{ failure() }}
         uses: actions/upload-artifact@v2
         with:
           name: Unix-failure
-          path: |
-            build/config.*
-            build/tests/**
-            !build/**/at-job-fifo.*
-            !build/**/*.lnk
+          path: build/tests/unix-testsuite.dir.tar.gz
